In [2]:
#Q1)
import numpy as np
arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [9]:
import numpy as np
lst1 = [4,8,1,0,3]
lst2 = [2,9,6,5,7]
arr1 = np.array(lst1)
arr2 = np.array(lst2)
print(arr1)
print(arr2)
arr = np.append(arr1,arr2, axis =0)
print(arr)
arrs = print(np.sort(arr))

[4 8 1 0 3]
[2 9 6 5 7]
[4 8 1 0 3 2 9 6 5 7]
[0 1 2 3 4 5 6 7 8 9]


In [10]:
#Q3)
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("No of Dimension:", arr.ndim)
print("size:",arr.size)
print("Array Type:", type(arr))


[[1 2 3]
 [4 5 6]]
No of Dimension: 2
size: 6
Array Type: <class 'numpy.ndarray'>


In [11]:
#Q4)
arr = np. array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Convert 1D array to a 2D numpy array of 2 rows and 3 columns.
arr2d = np. reshape(arr, (2, 5))
print(arr2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [16]:
#Q5)
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [17]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [19]:
#Q6)
input_list = [1, 2, 2, 5, 8, 4, 4, 8] 
l1 = []  
count = 0
for item in input_list: 
    if item not in l1: 
        count += 1
        l1.append(item) 
print("No of unique items are:", count)
print("unique items list:", l1)


No of unique items are: 5
unique items list: [1, 2, 5, 8, 4]
